CREATE TABLE IF NOT EXISTS public.inventory (
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make CHARACTER VARYING NOT NULL,
	inv_model CHARACTER VARYING NOT NULL, 
	inv_year character(4) NOT NULL, 
	inv_description TEXT NOT NULL, 
	inv_image CHARACTER VARYING NOT NULL, 
	inv_thumbnail CHARACTER VARYING NOT NULL, 
	inv_price NUMERIC(9,0) NOT NULL, 
	inv_miles integer NOT NULL, 
	inv_color CHARACTER VARYING NOT NULL, 
	classification_id integer NOT NULL, 
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);