CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

CREATE TABLE public.classification(
	classification_id INT GENERATED BY DEFAULT AS IDENTITY, 
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE IF NOT EXISTS public.inventory (
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_male CHARACTER VARYING NOT NULL,
	inv_model CHARACTER VARYING NOT NULL, 
	inv_year character(4) NOT NULL, 
	inv_description TEXT NOT NULL, 
	inv_image CHARACTER VARYING NOT NULL, 
	inv_thumbnail CHARACTER VARYING NOT NULL, 
	inv_price NUMERIC(9,0) NOT NULL, 
	inv_miles integer NOT NULL, 
	inv_color CHARACTER VARYING NOT NULL, 
	classification_id integer NOT NULL, 
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE 
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/')

UPDATE public.inventory
SET inv_thumbnail = REPLACE(inv_image, '/images/', '/images/')